# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='company',
            field=models.CharField(default='dev', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='job',
            field=models.CharField(default='dev', max_length=200),
            preserve_default=False,
        ),
    ]
