# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_works2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='techs',
            field=models.ManyToManyField(to='blog.Tech'),
        ),
    ]
